repos:
  - repo: local
    hooks:
      - id: "ruff"
        name: "ruff"
        language: "system"
        require_serial: true
        entry: "uv run ruff check"
        types: ["python"]
        stages: ["manual"]
      - id: "ruff-fix"
        name: "ruff-fix"
        language: "system"
        require_serial: true
        entry: "uv run ruff check --fix --show-fixes"
        types: ["python"]
      - id: "autopep8"
        name: "autopep8"
        language: "system"
        require_serial: true
        entry: "uv run autopep8 --global-config /dev/null --diff --exit-code"
        types: ["python"]
        stages: ["manual"]
      - id: "autopep8-fix"
        name: "autopep8-fix"
        language: "system"
        require_serial: true
        entry: "uv run autopep8 --global-config /dev/null -i"
        types: ["python"]
      - id: "flake8"
        name: "flake8"
        language: "system"
        require_serial: true
        entry: "uv run flake8"
        types: ["python"]
      - id: "ty"
        name: "ty"
        language: "system"
        require_serial: true
        entry: "uv run ty check ."
        types: ["python"]
        stages: ["manual"]
      - id: "mypy"
        name: "mypy"
        language: "system"
        require_serial: true
        entry: "uv run mypy --install-types --non-interactive --pretty ."
        pass_filenames: false
        types: ["python"]
      - id: "pyright"
        name: "pyright"
        language: "system"
        require_serial: true
        entry: "uv run pyright ."
        pass_filenames: false
        types: ["python"]
