repos:
  - repo: builtin
    hooks:
      # Trim trailing whitespace
      - id: trailing-whitespace
      # Ensure newline at EOF
      - id: end-of-file-fixer
      # Ensures that (non-binary) files with a shebang are executable
      - id: check-shebang-scripts-are-executable
      # Ensures that (non-binary) executables have a shebang
      - id: check-executables-have-shebangs
  - repo: local
    hooks:
      - id: "ruff"
        name: "ruff"
        language: "system"
        require_serial: true
        entry: "uv run ruff check"
        types: ["python"]
      - id: "flake8"
        name: "flake8"
        language: "system"
        require_serial: true
        entry: "uv run flake8"
        types: ["python"]
      - id: "mypy"
        name: "mypy"
        language: "system"
        require_serial: true
        entry: "uv run mypy --install-types --non-interactive ."
        pass_filenames: false
        types: ["python"]
      - id: "pyright"
        name: "pyright"
        language: "system"
        require_serial: true
        entry: "uv run pyright ."
        pass_filenames: false
        types: ["python"]
