[tools]
node = "22"
"npm:xo-cli" = "0.32.2"
# python = "3.8"
uv = "0.7"

[settings]
idiomatic_version_file_enable_tools = ["python"]

# [env]
# _.python.venv = { path = ".venv", create = true }

[tasks.xo-cli]
description = "run xo-cli"
run = "xo-cli"

[tasks.pytest]
description = "run tests"
run = "uv run pytest"

[tasks.jobs]
description = "manage test jobs"
run = "uv run ./jobs.py"

[tasks.lint]
description = "run linter and static analyzers"
depends = ["mypy", "pyright", "pycodestyle", "pydocstyle"]

[tasks.mypy]
description = "run mypy static analyzer"
run = "uv run mypy --install-types --non-interactive lib/ conftest.py pkgfixtures.py tests/"

[tasks.pyright]
description = "run pyright static analyzer"
run = "uv run pyright lib/ conftest.py pkgfixtures.py"

[tasks.pycodestyle]
description = "run pycodestyle style checker"
run = "uv run pycodestyle"

[tasks.pydocstyle]
description = "run pydocstyle style checker"
run = "uv run pydocstyle"

