name: Check coding style

on: [push]

jobs:
  pycodestyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jdx/mise-action@v2
      with:
        version: 2025.6.3
    - name: pycodestyle
      run: mise run pycodestyle

  # TODO: switch to uv once python has been updated to 3.10 or more 
  pydocstyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydocstyle
    - name: pydocstyle
      run: |
        pydocstyle
