name: Check jobs consistency

on: [push]

permissions: {}

jobs:
  jobs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./.github/actions/uv-setup/
        with:
          dev: false
      - name: Create a dummy data.py
        run: cp data.py-dist data.py
      - run: ./jobs.py check
