name: Check jobs consistency

on: [push]

jobs:
  jobs-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/base.txt
    - name: jobs-check
      run: ./jobs.py check
