name: Check jobs consistency

on: [push]

jobs:
  jobs-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jdx/mise-action@v2
      with:
        version: 2025.6.3
    - name: Create a dummy data.py
      run: cp data.py-dist data.py
    - name: jobs-check
      run: mise run jobs check
