name: Check requirements file consistency

on: [push, pull_request]

permissions: {}

jobs:
  requirements-check:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/uv-setup/
        with:
          dev: false
      - run: ./requirements/update_requirements.py
      - run: git diff --exit-code
